### ISSUE TITLE
leader-guide can not work with vim-gitgutter correctly

### ISSUE THREAD

**Issue by lecheel** [hecal3/vim-leader-guide#31]
here is simple vimrc
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

```
set nocompatible 
filetype off  
syntax on

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
"Plugin 'tpope/vim-fugitive'
Plugin 'hecal3/vim-leader-guide'
Plugin 'airblade/vim-gitgutter'
call vundle#end()          
filetype plugin indent on 

let mapleader=","

nmap <leader>n :GitGutterNextHunk<cr>
nmap <leader>p :GitGutterPrevHunk<cr>

nmap <leader>e :e .<cr> 
nmap <leader>tg :GitGutterToggle<cr> 


let g:all_key_map    = {}
let g:leader_key_map = {}
let g:all_key_map['<leader>']         = g:leader_key_map
let g:all_key_map['<leader>']['name'] = '<leader>'
nmap <silent> <leader> :<c-u>LeaderGuide '<leader>'<CR>
vmap <silent> <leader> :<c-u>LeaderGuideVisual '<leader>'<CR>
```
,n work correctly w/o popup the LeaderGuide hint
if press "," until LeaderGuide popup then "n" GitGutterNextHunk is not working

**Comment by hecal3** [comment]
Thanks.
This should be fixed with the latest commit.

Gitgutter is running some autocommands on buffer or window changes.
One of those probably failed and aborted when trying to analyse the guide buffer. The plugin stopped working as a result.

I added some noautocmd to the window and buffer commands to avoid triggering autocommands for the guide buffer.
